#!/usr/bin/env bash
# Pings an IP address passed as an argument
# Pings 5 times or displays a message if
#+ no argument passed

if [ $# -eq 0 ] # no args == 0
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
