#!/usr/bin/env bash
# Displays a text string infintely
#+ and another when receives a SIGTERM signal

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap "echo 'I am invincible!!!'" SIGTERM
done
