#!/usr/bin/env bash
# Displays the content of a file

# cat /etc/passwd | cut -d ":" -f 1,3,7
if [ -r /etc/passwd ]
then
    while read -r line
    do
        echo "$line" | cut -d ":" -f 1,3,7
    done < /etc/passwd  # take input from here
fi
