#!/usr/bin/env bash
# This script displays "Best School" 10 times

count=1

while (( count <= 10 ))
do
    echo "Best School"
    if (( count == 9 ))
    then
        echo "Hi"
    fi
    ((count++))
done
