#!/usr/bin/env bash
# This scirpt displays the time for 12hours and 59mins

hour=0
min=1

while (( hour <= 12 ))
do
    echo "Hour: $hour"
    min=1
    while (( min <= 59 ))
    do
        echo "$min"
        (( min++ ))
    done
    (( hour++ ))
done
